language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

install: travis_retry composer install

script: composer ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
